# Generated by Django 5.0 on 2025-04-04 10:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients_docs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilpatient",
            name="age",
            field=models.IntegerField(default=0, verbose_name="Âge"),
        ),
        migrations.AddField(
            model_name="profilpatient",
            name="date_naissance",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Date de naissance"
            ),
        ),
    ]
