# Generated by Django 5.0 on 2025-04-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients_docs", "0002_profilpatient_age_profilpatient_date_naissance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilpatient",
            name="date_de_rdv",
            field=models.DateField(verbose_name="Date d'entretien"),
        ),
    ]
