# Generated by Django 5.0 on 2025-04-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients_docs", "0003_alter_profilpatient_date_de_rdv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilpatient",
            name="numero_telephone_1",
            field=models.CharField(max_length=10, verbose_name="Numéro de téléphone 1"),
        ),
        migrations.AlterField(
            model_name="profilpatient",
            name="numero_telephone_2",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Numéro de téléphone 2",
            ),
        ),
    ]
