# Generated by Django 5.1.7 on 2025-04-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients_docs", "0005_remove_profilpatient_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Generaliste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "prenom",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Nom"
                    ),
                ),
                (
                    "adresse",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Adresse"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Téléphone"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Orthophoniste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "prenom",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Nom"
                    ),
                ),
                (
                    "adresse",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Adresse"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Téléphone"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Psychologue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Nom")),
                (
                    "prenom",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Nom"
                    ),
                ),
                (
                    "adresse",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Adresse"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Téléphone"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
