# Generated by Django 5.1.7 on 2025-04-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients_docs", "0006_generaliste_orthophoniste_psychologue"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilpatient",
            name="lieu_naissance",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="lieu de naissance"
            ),
        ),
    ]
