# Generated by Django 5.1.7 on 2025-04-09 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients_docs", "0007_profilpatient_lieu_naissance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilpatient",
            name="alimentation_enfant",
            field=models.CharField(
                blank=True,
                choices=[("Naturelle", "طبيعية"), ("Artificielle", "اصطناعية")],
                default="طبيعية",
                max_length=200,
                null=True,
                verbose_name="تغدية الطفل",
            ),
        ),
        migrations.AlterField(
            model_name="profilpatient",
            name="date_de_rdv",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                null=True,
                verbose_name="Date d'entretien",
            ),
        ),
    ]
