# Generated by Django 5.1.7 on 2025-04-11 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients_docs", "0009_alter_profilpatient_alimentation_enfant"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Generaliste",
        ),
        migrations.DeleteModel(
            name="Orthophoniste",
        ),
        migrations.DeleteModel(
            name="Psychologue",
        ),
        migrations.RemoveField(
            model_name="profilpatient",
            name="lieu_naissance",
        ),
        migrations.AlterField(
            model_name="profilpatient",
            name="alimentation_enfant",
            field=models.CharField(
                blank=True,
                choices=[("Naturelle", "طبيعية"), ("Artificielle", "اصطناعية")],
                default="Inconnu",
                max_length=200,
                null=True,
                verbose_name="تغدية الطفل",
            ),
        ),
        migrations.AlterField(
            model_name="profilpatient",
            name="date_de_rdv",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Date d'entretien"
            ),
        ),
    ]
