# Generated by Django 5.1.7 on 2025-04-11 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients_docs", "0010_delete_generaliste_delete_orthophoniste_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilpatient",
            name="lieu_naissance",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Lieu de naissance"
            ),
        ),
        migrations.AlterField(
            model_name="profilpatient",
            name="alimentation_enfant",
            field=models.CharField(
                blank=True,
                choices=[("Naturelle", "طبيعية"), ("Artificielle", "اصطناعية")],
                default="Naturelle",
                max_length=200,
                null=True,
                verbose_name="تغدية الطفل",
            ),
        ),
        migrations.AlterField(
            model_name="profilpatient",
            name="date_de_rdv",
            field=models.DateField(
                blank=True,
                default=datetime.date.today,
                null=True,
                verbose_name="Date d'entretien",
            ),
        ),
    ]
