# Generated by Django 5.1.7 on 2025-04-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients_docs", "0011_profilpatient_lieu_naissance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilpatient",
            name="date_de_rdv",
        ),
    ]
