# Generated by Django 5.1.7 on 2025-04-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients_docs", "0013_profilpatient_prenom_mere_profilpatient_prenom_pere"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilpatient",
            name="prenom_mere",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Prénom de la mère"
            ),
        ),
        migrations.AlterField(
            model_name="profilpatient",
            name="prenom_pere",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Prénom du père"
            ),
        ),
    ]
