# Generated by Django 5.1.7 on 2025-04-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients_docs", "0014_alter_profilpatient_prenom_mere_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilpatient",
            name="nom",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nom"
            ),
        ),
        migrations.AlterField(
            model_name="profilpatient",
            name="prenom",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Prénom"
            ),
        ),
    ]
