# Generated by Django 5.1.7 on 2025-04-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vitrine", "0002_alter_customuser_added_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="added_by",
        ),
    ]
