# Generated by Django 5.1.7 on 2025-04-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vitrine", "0003_alter_customuser_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="nom_medcin",
            new_name="nom_medecin",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="prenom_medcin",
            new_name="prenom_medecin",
        ),
    ]
