# Generated by Django 5.1.7 on 2025-04-13 16:54

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rendezvous",
            options={},
        ),
        migrations.RemoveField(
            model_name="rendezvous",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="rendezvous",
            name="docteur",
        ),
        migrations.RemoveField(
            model_name="rendezvous",
            name="motif",
        ),
        migrations.RemoveField(
            model_name="rendezvous",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="rendezvous",
            name="status",
        ),
        migrations.RemoveField(
            model_name="rendezvous",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="cree_le",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                null=True,
                verbose_name="Créé le",
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Notes / Description"
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="duree",
            field=models.DurationField(
                default=datetime.timedelta(seconds=1800), verbose_name="Durée prévue"
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email du patient"
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="est_paye",
            field=models.BooleanField(default=False, verbose_name="Payé ?"),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="modifie_le",
            field=models.DateTimeField(auto_now=True, verbose_name="Modifié le"),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="nom_patient",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Nom du patient"
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="prix",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Prix (€)",
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="statut",
            field=models.CharField(
                choices=[
                    ("prévu", "Prévu"),
                    ("terminé", "Terminé"),
                    ("annulé", "Annulé"),
                    ("reporté", "Reporté"),
                ],
                default="prévu",
                max_length=10,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="teleconsultation",
            field=models.BooleanField(default=False, verbose_name="Téléconsultation ?"),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="telephone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Téléphone du patient",
            ),
        ),
        migrations.AddField(
            model_name="rendezvous",
            name="type_seance",
            field=models.CharField(
                choices=[
                    ("évaluation", "Évaluation"),
                    ("rééducation", "Rééducation"),
                    ("suivi", "Suivi"),
                    ("consultation", "Consultation"),
                ],
                max_length=20,
                null=True,
                verbose_name="Type de séance",
            ),
        ),
        migrations.AlterField(
            model_name="rendezvous",
            name="date",
            field=models.DateField(verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="rendezvous",
            name="heure",
            field=models.TimeField(verbose_name="Heure"),
        ),
    ]
